### ISSUE TITLE
Package scripts

### ISSUE THREAD

**Issue by sundowndev** [blyndusk/pwgn-cli#2]
This

https://github.com/blyndusk/pwgn-cli/blob/be00de0117f4faad96292d1b60d7d6d5a9c5ac8e/package.json#L6-L13

Shouldn't it be :

```json
"scripts": { 
     "lint": "tslint -c tslint.json -p tsconfig.json", 
     "lint:fix": "npm run lint -- --fix", 
     "build": "webpack && node scripts/build.js", 
     "test": "jest", 
     "test:watch": "jest --watch", 
     "start": "npm run build && npm test -- --watchAll" 
 }, 
```

?

----

CI should then have 3 stages IMO:

```
    - name: install & build
      run: |
        npm install
        npm run build --if-present
    - name: lint
      run: npm run lint
    - name: test
      run: npm test --if-present
```

**Comment by blyndusk** [comment]
## NPM scripts

Thank you, previously I did not understand the difference between using the dev dependencies directly in **the terminal**:
```bash
$ ./node_modules/.bin/bar
``` 
and in a **NPM script**:
```bash
"scripts": {
	"foo": "bar"
}
```
, but I get it now thanks to this [article](https://firstdoit.com/no-need-for-globals-using-npm-dependencies-in-npm-scripts-3dfb478908) and more precisely this **highlight**:

> npm has another trick up its sleeve. When evaluating scripts, npm adds `node_modules/.bin/` to the PATH environment variable. That means you can forego the folder prefix entirely!

------

## Github Actions

@sundowndev Should not we check if all scripts exist in the course of actions?

I mean, except the `build` script, they could all be optionnal.

**Comment by blyndusk** [comment]
Make sense.

Besides, it would be more logical to lint the files **before** build, right?

So it should be `lint>build>test` instead of `build>lint>test` IMO.

**Comment by sundowndev** [comment]
@blyndusk Yes, lint job should be run first :)
